name: Test and Publish to PyPI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run tests in Docker
      run: |
        docker build -t pyindi-client .
        docker run --rm pyindi-client

  publish:
    needs: test
    if: github.event_name == 'release' && github.event.action == 'published'
    
    runs-on: ubuntu-latest
    permissions:
      # Required for OIDC publishing to PyPI
      id-token: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo add-apt-repository -y ppa:mutlaqja/ppa
        sudo apt-get install -y libindi-dev swig python3-dev
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build package
      run: python -m build
    
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
